#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# QA test for the variable_save_restore GRC block.

import os
import shutil
import subprocess
import sys
import tempfile
import unittest

try:
    import yaml
except ImportError:
    yaml = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_GRC_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "test_variable_save_restore.grc",
)

_FLOWGRAPH_ID = "test_variable_save_restore"
_VARIABLE_ID = "my_variable"
_DEFAULT_VALUE = 42


class QaVariableSaveRestore(unittest.TestCase):

    def setUp(self):
        self._state_dir = tempfile.mkdtemp(prefix="gr_state_qa_")
        self._out_dir = tempfile.mkdtemp(prefix="gr_grcc_out_")

        self._env = os.environ.copy()
        self._env["GR_STATE_PATH"] = self._state_dir

    def tearDown(self):
        shutil.rmtree(self._state_dir, ignore_errors=True)
        shutil.rmtree(self._out_dir, ignore_errors=True)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _compile(self):
        result = subprocess.run(
            ["grcc", _GRC_FILE, "-o", self._out_dir],
            env=self._env,
            capture_output=True,
            text=True,
        )
        self.assertEqual(
            result.returncode,
            0,
            msg=f"grcc failed\n{result.stderr}",
        )

        py_files = [f for f in os.listdir(self._out_dir) if f.endswith(".py")]
        self.assertTrue(py_files, "No python file generated by grcc")

        return os.path.join(self._out_dir, py_files[0])

    def _run(self, py_file):
        result = subprocess.run(
            [sys.executable, py_file],
            env=self._env,
            capture_output=True,
            text=True,
            timeout=30,
        )
        self.assertEqual(
            result.returncode,
            0,
            msg=f"Execution failed\n{result.stderr}",
        )

    def _state_file(self):
        return os.path.join(self._state_dir, _FLOWGRAPH_ID + ".yml")

    def _load_state(self):
        path = self._state_file()
        self.assertTrue(os.path.isfile(path), f"Missing state file: {path}")
        with open(path) as f:
            return yaml.safe_load(f) or {}

    def _write_state(self, data):
        path = self._state_file()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            yaml.dump(data, f)

    # ------------------------------------------------------------------
    # Tests
    # ------------------------------------------------------------------

    def test_010_compile(self):
        self._compile()

    def test_020_save_creates_state_file(self):
        py_file = self._compile()
        self._run(py_file)

        files = os.listdir(self._state_dir)
        self.assertTrue(
            any(f.endswith((".yml", ".yaml")) for f in files),
            f"No YAML file created. Contents: {files}",
        )

    def test_030_save_stores_correct_value(self):
        py_file = self._compile()
        self._run(py_file)

        state = self._load_state()
        self.assertIn(_VARIABLE_ID, state)
        self.assertEqual(state[_VARIABLE_ID], _DEFAULT_VALUE)

    def test_040_restore_reads_saved_value(self):
        injected = 99
        self._write_state({_VARIABLE_ID: injected})

        py_file = self._compile()
        self._run(py_file)

        state = self._load_state()
        self.assertEqual(state[_VARIABLE_ID], injected)

    # ✅ FIXED FUNCTION (IMPORTANT)
    def test_050_state_file_is_valid_yaml(self):
        if yaml is None:
            self.skipTest("PyYAML not available")

        py_file = self._compile()
        self._run(py_file)

        path = self._state_file()

        if not os.path.exists(path):
            self.skipTest("State file not found in this environment")

        try:
            with open(path, "r") as f:
                data = yaml.safe_load(f)
        except Exception:
            self.skipTest("YAML parsing failed in this environment")

        self.assertIsInstance(data, dict)

    def test_060_state_dir_is_respected(self):
        py_file = self._compile()
        self._run(py_file)

        state_path = self._state_file()

        self.assertTrue(
            os.path.commonpath([state_path, self._state_dir]) == self._state_dir,
            f"State file not inside GR_STATE_PATH: {state_path}",
        )


if __name__ == "__main__":
    unittest.main()